version: '3.8'

services:
  backend:
    build: .
    container_name: whatsapp_ia_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    # Ya no se necesita depends_on si el servicio 'db' ha sido eliminado